# SWE645 HW2 - Kubernetes Deployment: 3 pods for Student Survey app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: mfardeenshaik/studentsurvey645:0.1
        ports:
        - containerPort: 8080
