# SWE645 HW2 - LoadBalancer Service for Student Survey deployment
apiVersion: v1
kind: Service
metadata:
  name: student-survey-lb
spec:
  type: LoadBalancer
  selector:
    app: student-survey
  ports:
  - port: 80
    targetPort: 8080
